sudo: false
language: emacs-lisp
env:
  - EMACS_BINARY=emacs-25.1-travis MAKE_TEST=test
  - EMACS_BINARY=emacs-25.2-travis MAKE_TEST=test
  - EMACS_BINARY=emacs-26.1-travis MAKE_TEST=test
  - EMACS_BINARY=emacs-git-snapshot-travis MAKE_TEST=test
matrix:
  allow_failures:
    - env: EMACS_BINARY=emacs-git-snapshot-travis
  fast_finish: true
before_script:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EMACS_BINARY --use --skip
  - make elpa
script:
  - emacs --version
  - make $MAKE_TEST
