site_name: "Projectile: The Project Interaction Library for Emacs"
repo_url: https://github.com/bbatsov/projectile
site_favicon: favicon.ico
copyright: "Copyright (C) 2011-2019 Bozhidar Batsov and Projectile contributors"
docs_dir: doc
pages:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Projects: projects.md
- Configuration: configuration.md
- Extensions: extensions.md
- FAQ: faq.md
- Troubleshooting: troubleshooting.md
- Contributing: contributing.md
- Support: support.md
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
theme: readthedocs
