site_name: "Projectile"
repo_url: https://github.com/bbatsov/projectile
site_favicon: favicon.ico
copyright: "Copyright (C) 2017 Bozhidar Batsov and Projectile contributors"
docs_dir: doc
pages:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Configuration: configuration.md
- Contributing: contributing.md
- Support: support.md
extra_css:
  - css/extra.css
theme: readthedocs
